"""
Python package markdown is used to convert markdown to html.
FenceCodeExtension and CodeHiliteExtension are used to better format code in markdown.

CodeHiliteExtension uses pygments to add style to codes.
The style.css file is generated by pygments using command `pygmentize -S monokai -f html -a .codehilite > style.css`
monokai is the theme for code styling. we can use `pygmentize -L style` to see all available themes.

Remember to delete `pre { line-height: 125%; }` in the generated css file because it causes QLabel to display it poorly.
"""

import markdown
from markdown.extensions.codehilite import CodeHiliteExtension
from markdown.extensions.fenced_code import FencedCodeExtension

from setting.setting_reader import setting


class MarkdownParser:
    def __init__(self, custom_style: str = ''):
        self.markdown_instance = markdown.Markdown(extensions=[FencedCodeExtension(), CodeHiliteExtension()])
        self.style = self._load_style(custom_style=custom_style)

    @staticmethod
    def _load_style(custom_style: str = ''):
        with open(setting.root_path / 'backend/tools/markdown_parser/style.css', 'r', encoding='utf-8') as f:
            code_style = ''.join([line for line in f.readlines() if not line.startswith('pre {')])
            code_style += """
                .codehilite {
                    margin: 5px 10px;
                }
               """
        style = code_style + custom_style
        return style

    def add_style(self, style: str):
        self.style += style
        return self

    def to_html(self, markdown_text):
        html = self.markdown_instance.convert(markdown_text)
        final_html = f"""
        <style>{self.style}</style>
        {html}
        """
        return final_html
